[package]
name = "l2_order_book"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.10", features = ["derive"] }
clap_derive = "4.5.8"
